### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by vsposato** [wiverson/desktop-spring-boot#2]
This repository says that it is a desktop with Spring Boot, but I don't see anywhere in the project any Spring dependencies, configuration, etc. Am I missing something or did you never actually complete it? It looks like it is simply based off the template.

**Comment by wiverson** [comment]
You guessed it - this was (is?) something that I thought might be interesting and then I wound up not going forward on it.

The premise: a pre-built template combining the JavaFX web engine with Spring Boot to make an easy, out-of-the-box, sort of equivalent to Electron but for Spring Boot devs.

Pros: would be a nice way to package a Spring Boot app as a desktop app. Java and Spring Boot are very popular.

Cons: No mobile path. Minimum app size would be 40mb+. 

I wound up switching to using SvelteKit + Capacitor + Tauri and tbh I'm finding the overall dev experience to be a lot nicer than Spring Boot. I think Spring Boot for REST is fine (esp because of the wide Java ecosystem) but integration of client side JS and Spring Boot is a PITA.

That said, if anyone wants to throw some $ my way I'd be happy to finish this out. :)
